version: '3.8'

services:
  api:
    build: ./app/
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    restart: always
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=meu_bairro_dev
    ports:
      - 5432:5432


volumes:
  postgres_data: